name: Deploy web app
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Install new NodeJS
              uses: actions/setup-node@v3  
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Run the tests
              run: npm test
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: Get the code
              uses: actions/checkout@v3
            - name: Install new NodeJS
              uses: actions/setup-node@v3  
              with:
                node-version: 18
            - name: Install dependencies
              run: npm ci
            - name: Build project
              run: npm run build
            - name: Upload to web host
              run: echo "Uploading..."
